[package]
name = "shrike"
version = "0.1.0"
edition = "2021"

[dependencies]
futures-util = "0.3"
regex = "1.5"
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.15"
warp = "0.3"